### ISSUE TITLE
Perhaps this needs to be improved, or at least documented

### ISSUE THREAD

**Issue by avianna** [tm-kn/django-basic-auth-ip-whitelist#7]
https://github.com/tm-kn/django-basic-auth-ip-whitelist/blob/318006b15b598c035cf52031c8fa63dbf241440f/baipw/utils.py#L23

This is the situation:
- this default get_client_ip is called by self._get_client_ip()
- which takes whatever this returns and passes it to ipaddress.ip_address()
- which doesn't accept None as an input
- so if this code path is hit, ipaddress.ip_address() will exception out
- but baipw doesn't handle this exception, so it just escalates up, and the whole app just ends up 500-ing.

So this code path is problematic, if there isn't a saner return, then at least maybe warn others that if this code branch is hit, the app will blow up.

**Comment by tm-kn** [comment]
I have a plan to re-work getting the IP. The current way is quite flimsy as you've noticed yourself.

**Comment by tm-kn** [comment]
Closing in favour of #9. Pull requests welcome if you want to update the documentation.
